#!/usr/bin/env bash
# Capture a callgrind profile of the headless console binary under a
# synthetic operator workload + annotate the top-N functions by
# inclusive cost to a text report committed to the repo.
#
# Why callgrind and not perf:
#   - perf needs kernel access (CAP_SYS_ADMIN or paranoid<2). On WSL2
#     the default kernel does not expose perf counters; on a CI runner
#     the same applies. callgrind is purely userspace (Valgrind), works
#     anywhere Valgrind does -- including the existing CI gate.
#   - callgrind is deterministic. Sampling profilers (perf, gperftools)
#     pick up the wrong picture if the workload is short / load is
#     bursty. The portfolio cares about RELATIVE distribution, which
#     callgrind nails by counting every basic block executed.
#   - callgrind output already lands in a stable file format we can
#     diff between releases -- portable across machines.
#
# The trade-off: callgrind is ~50x slower than native execution. A
# workload that takes 2s on the bare metal takes ~100s under
# instrumentation. Not a concern for one-shot baseline capture;
# acceptable for CI if the workload is kept tight.
#
# Usage:
#   ./scripts/perf/capture-callgrind.sh
#       (assumes build/wsl-release/industrial-hmi-console exists)
#
#   BINARY=./build/release/industrial-hmi-console \
#   WORKLOAD=./scripts/perf/workload-baseline.txt \
#       ./scripts/perf/capture-callgrind.sh
#
# Output:
#   scripts/perf/output/callgrind.out.<pid>          raw callgrind file
#   scripts/perf/output/callgrind-annotate.txt       top functions by cost
#
# The annotate file is what you commit + diff against future releases.
# The raw .out file is gitignored (regenerated by anyone re-running).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BINARY="${BINARY:-$REPO_ROOT/build/wsl-release/industrial-hmi-console}"
WORKLOAD="${WORKLOAD:-$REPO_ROOT/scripts/perf/workload-baseline.txt}"
OUT_DIR="$REPO_ROOT/scripts/perf/output"

if [[ ! -x "$BINARY" ]]; then
    echo "error: binary not found or not executable: $BINARY" >&2
    echo "build it first:" >&2
    echo "    cmake --preset release && cmake --build build/wsl-release -j" >&2
    exit 1
fi

if [[ ! -r "$WORKLOAD" ]]; then
    echo "error: workload script not readable: $WORKLOAD" >&2
    exit 1
fi

if ! command -v valgrind >/dev/null; then
    echo "error: valgrind not installed" >&2
    echo "    sudo apt install valgrind" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# --tool=callgrind          basic-block sampler
# --callgrind-out-file      stable location (vs ./callgrind.out.<pid>)
# --collect-jumps=yes       branch-level cost; lets callgrind_annotate
#                           show within-function hotspots
# --dump-instr=yes          per-instruction cost (negligible overhead
#                           given we are already 50x slow)
# --cache-sim=no            skip L1/L2/LL cache simulation -- another
#                           5-10x slowdown, not what we are measuring
OUT_RAW="$OUT_DIR/callgrind.out"
echo "running callgrind on $BINARY under $WORKLOAD ..."
valgrind \
    --tool=callgrind \
    --callgrind-out-file="$OUT_RAW" \
    --collect-jumps=yes \
    --dump-instr=yes \
    --cache-sim=no \
    --quiet \
    "$BINARY" \
    < "$WORKLOAD" \
    > "$OUT_DIR/console-stdout.txt" 2>&1 || true

if [[ ! -s "$OUT_RAW" ]]; then
    echo "error: callgrind produced no output. Inspect:" >&2
    echo "    $OUT_DIR/console-stdout.txt" >&2
    exit 2
fi

# Annotate top 100 functions by inclusive cost (Ir = instructions read).
# The percentage column on the right of each row is the share of total
# instructions executed -- that is the contract we diff between
# baselines.
ANNOTATE_OUT="$OUT_DIR/callgrind-annotate.txt"
callgrind_annotate \
    --threshold=99 \
    --auto=no \
    "$OUT_RAW" \
    > "$ANNOTATE_OUT"

echo "captured."
echo "  raw:      $OUT_RAW"
echo "  annotate: $ANNOTATE_OUT"
echo ""
echo "top 15 functions by inclusive Ir:"
echo ""
grep -E '^\s*[0-9,]+\s+\(' "$ANNOTATE_OUT" | head -15
